FROM ubuntu:18.04

MAINTAINER ALexander Somik 

RUN -yqq

RUN sudo apt-get -yqq install apt-transport-https ca-certificates dirmngr

RUN sudo apt-key -yqq adv --keyserver hkp://keyserver.ubuntu.com:80 --recv E0C56BD4

RUN echo "deb https://repo.clickhouse.tech/deb/stable/ main/" | sudo tee /etc/apt/sources.list.d/clickhouse.list

RUN sudo apt-get update

RUN sudo apt-get install -y clickhouse-server clickhouse-client



EXPOSE 5000

sudo apt-get install apt-transport-https ca-certificates dirmngr
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv E0C56BD4

echo "deb https://repo.clickhouse.tech/deb/stable/ main/" | sudo tee \
    /etc/apt/sources.list.d/clickhouse.list
sudo apt-get update

sudo apt-get install -y clickhouse-server clickhouse-client

sudo service clickhouse-server start
