#!/bin/bash

#
docker build -t aquafeet/client_ch .

#
docker network create foodtrucks

#
docker run  -d --net foodtrucks -p 9000:9000  --ulimit nofile=262144:262144 --name ch yandex/clickhouse-server

#
docker run   --net foodtrucks -p 5000:5000  aquafeet/client_ch

docker run  -p 8080:8080 -v /home/aquafeet/dep/DE_airflow/clickhouse/client_place/:/usr/local/airflow/dags -v /home/aquafeet/dep/data:/opt/data  puckel/docker-airflow webserver
